name: Nightly

on:
  schedule:
      - cron:  '0 12 * * *'
  workflow_dispatch:

jobs:
  docgen:
    name: Generate Reference Docs
    if: github.repository_owner == 'withastro'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code using Git
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run docgen script
        run: pnpm run docgen

      - name: Create Pull Request
        id: createpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ci/docgen
          token: ${{ secrets.NIGHTLY_PERSONAL_GITHUB_TOKEN }}
          add-paths: src/pages/en/*.md
          commit-message: 'ci: update reference docs'
          title: 'ci: update reference docs'
          body: |
            This PR is auto-generated by a nightly GitHub action to update the reference docs from source code in withastro/astro.
          labels: ci
